substitutions:
  name: serin-cn105
  friendly_name: "Serin Heat Pump Controller"
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true

  project:
    name: "serin.cn105"
    version: "0.1"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
    level: INFO  

api:

ota:
  - platform: esphome

wifi:
  ap:
    ssid: "Serin Setup"
    password: "serincn105"

captive_portal:

external_components:
  - source: github://akifbayram/MitsubishiCN105ESPHome

dashboard_import:
  package_import_url: github://akifbayram/MitsubishiCN105ESPHome/atoms3/serin.yaml@0.1
  import_full_config: false

packages:
  cn105: !include common/cn105.yaml