substitutions:
  name: serin-cn105
  friendly_name: "Serin Heat Pump Controller" 

logger:
    level: INFO 

api:

ota:
  - platform: esphome

wifi:

dashboard_import:
  package_import_url: github://akifbayram/MitsubishiCN105ESPHome/atoms3/serin.yaml
  import_full_config: false
  
external_components:
  - source: github://akifbayram/MitsubishiCN105ESPHome

packages:
  cn105: github://akifbayram/MitsubishiCN105ESPHome/atoms3/common/cn105.yaml
  esp32s3: github://akifbayram/MitsubishiCN105ESPHome/atoms3/common/esp32s3.yaml
  wifi: github://akifbayram/MitsubishiCN105ESPHome/atoms3/common/wifi.yaml
  web_server: github://akifbayram/MitsubishiCN105ESPHome/atoms3/common/web_server.yaml