substitutions:
  name: serin-cn105
  friendly_name: "Serin Heat Pump Controller"
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true

  project:
    name: "serin.cn105"
    version: "0.1"

logger:
    level: INFO 

improv_serial: 

api:

ota:
  - platform: esphome

wifi:
  ap:
    ssid: "Serin Setup"
    password: "serincn105"

web_server:
  version: 3

captive_portal:

external_components:
  - source: github://akifbayram/MitsubishiCN105ESPHome

dashboard_import:
  package_import_url: github://akifbayram/MitsubishiCN105ESPHome/atoms3/serin.yaml@main
  import_full_config: false

packages:
  esp32s3: !include common/esp32s3.yaml
  cn105: !include common/cn105.yaml