esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true

  project:
    name: "serin.cn105"
    version: "0.1"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO2
  rx_pin: GPIO1